services:
  haproxy:
    image: haproxy:lts-trixie
    container_name: haproxy
    user: root
    dns: 8.8.8.8
    network_mode: host
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Tehran
    cap_add:
      - NET_ADMIN
      - SYS_RESOURCE
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - .:/workspaces/codespace-haproxy:cached
      - ./sysctl.d/99-optimize.conf:/etc/sysctl.d:ro
      - ./config:/usr/local/etc/haproxy:ro
